#!/bin/bash

read -p "Enter any 1st three digit number: " num1
read -p "Enter any 2nd three digit number: " num2
read -p "Enter any 3rd three digit number: " num3
read -p "Enter any 4th three digit number: " num4
read -p "Enter any 5th three digit number: " num5

if (( $num1 -lt $num2; $num1 -lt $num3; $num1 -lt $num4; $num1 -lt $num5; ))
then
echo "$num1 is the minimum number"
elif [ $num2 -lt $num1; $num2 -lt $num3; $num2 -lt $num4; $num2 -lt $num5;]
then
echo "$num2 is the minimum number"

elif [$num3 -lt $num1; $num3 -lt $num2; $num3 -lt $num4; $num3 -lt $num5;]
then
echo "$num3 is the minimum number"

elif [$num4 -lt $num1; $num4 -lt $num2; $num4 -lt $num3; $num4 -lt $num5;]
then
echo  "$num4 is the minimum number"

elif [$num5 -lt $num1; $num5 -lt $num2; $num5 -lt $num3; $num5 -lt $num4;]
then
echo "$num5 is the minimum number"

fi

#for maximum number


if [ $num1 -gt $num2; $num1 -gt $num3; $num1 -gt $num4; $num1 -gt $num5; ]
then
echo "$num1 is the maximum number"
elif [ $num2 -gt $num1; $num2 -gt $num3; $num2 -gt $num4; $num2 -gt $num5;]
then
echo "$num2 is the maximum number"

elif [$num3 -gt $num1; $num3 -gt $num2; $num3 -gt $num4; $num3 -gt $num5;]
then
echo "$num3 is the maximum number"

elif [$num4 -gt $num1; $num4 -gt $num2; $num4 -gt $num3; $num4 -gt $num5;]
then
echo  "$num4 is the maximum number"

elif [$num5 -gt $num1; $num5 -gt $num2; $num5 -gt $num3; $num5 -gt $num4;]
then
echo "$num5 is the maxmum number"

fi

